[package]
name = "shouxtech/input-categorizer"
description = "Observe the preferred input category of the player"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "default.project.json", "wally.toml", "wally.lock"]
exclude = ["**"]

[dependencies]
Charm = "littensy/charm@0.10.0"